# EJERCICIO TITANIC

![](https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/RMS_Titanic_3.jpg/800px-RMS_Titanic_3.jpg)

Para el ejercicio final, intentá combinar todas las habilidades que aprendiste hasta ahora para cumplir las consignas. **Sentite libre de desviarte de las consignas y explorar los datos que te parezcan interesantes.**

**Link dataset**: https://raw.githubusercontent.com/PPereyraAN/Cursos/main/titanic.csv

Este archivo contiene información sobre todos los pasajeros y tripulantes del RMS Titanic. Sus columnas son:

- ``name``: strings with the name of the passenger.
- ``gender``: "male" or "female".
- ``age``: a float with the persons age on the day of the sinking. The age of babies (under 12 months) is given as a fraction of one year.
- ``class``: a string specifying the class (1st, 2nd or 3rd) for passengers or the type of service aboard for crew members.
- ``embarked``: the persons place of of embarkment.
- ``country``: the persons home country.
- ``ticketno``: the persons ticket number (NA for crew members).
- ``fare``: the ticket price (NA for crew members, musicians and employees of the shipyard company).
- ``sibsp``: a number specifying the number if siblings/spouses aboard.
- ``parch``: a number specifying the number of parents/children aboard.
- ``survived``: a string ("no" or "yes") specifying whether the person has survived the sinking.

In [ ]:
import pandas as pd
url = "https://raw.githubusercontent.com/PPereyraAN/Cursos/main/titanic.csv"

***Leer el dataset y mostrar:***

- ***Los primeros 5 registros***
- ***Los ultimos 5 registros***

***¿Cuantas filas y columnas tiene el dataset?***

***Cambiar el nombre de la columna ```age``` por ```edad```***

***Aplicar un ```describe``` y sacar por lo menos 3 conclusiones***

***¿Cuales son las personas que tienen los tickets con mayores precio?***

***Contar la cantidad de personas por genero***

***¿De cuantos paises diferentes provenian las personas?***

***Encontrar la edad promedio de todas las personas a bordo***

***Filtrar solo los hombres, de primera clase, que sean de Estados unidos o Inglaterra. Finalmente ordenarlos por el precio del ticket***

***Contar cuantas personas murieron o sobrevivieron que no sean ni de Estados unidos ni de Inglaterra***

***Encontrar la edad promedio de los hombres a bordo***

***Seleccionar solo las personas que pertenezca a la clase '3rd', luego contar cuantos sobrevivieron y cuantos murieron.***

***Tarifa promedio correspondiente a cada tipo de clase***

***Encuentre la tasa de supervivencia promedio correspondiente a cada tipo de cabina***